version: '3.8'

services:
  postgres:
    container_name: just_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data
    command: postgres -N 500

volumes:
  my_db_data: